<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.junoyi</groupId>
        <artifactId>junoyi-module-api</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>junoyi-module-platform-api</artifactId>
    <description> 第三方平台（企业微信、飞书、钉钉）接入API模块, 供其他模块相当于SDK提供接口供其他模块调用解耦 </description>

    <dependencies>
        <dependency>
            <groupId>com.junoyi</groupId>
            <artifactId>junoyi-framework-boot-starter</artifactId>
        </dependency>
    </dependencies>

</project>